name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/DockerHub-Description.yml
jobs:
  dockerHubDescription:
    if: startsWith(github.repository, 'huxuesen/ddocr-docker')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: huxuesen/ddocr
        short-description: ${{ github.event.repository.description }}# This is the short description that will be displayed on Docker Hub.